In [77]:
import pandas as pd
import numpy as np
dfb=pd.read_csv('temp_files\\df_prices_before_fill.csv')
dfb.set_index(['date', 'permno'], inplace=True)
dfa=pd.read_csv('temp_files\\df_prices_after_fill.csv')
dfa.set_index(['date', 'permno'], inplace=True)
def map_permno_to_ticker(df):
    # Reset index to access permno and date as columns
    df_reset = df.reset_index()

    # Check required columns existence
    if 'permno' not in df_reset.columns or 'ticker' not in df_reset.columns:
        raise ValueError("Input dataframe must contain 'permno' and 'ticker' columns in index or columns.")

    # Drop duplicates of permno and ticker pairs to get unique mappings
    unique_mappings = df_reset[['permno', 'ticker']].drop_duplicates()

    df_reset = df.reset_index() if isinstance(df.index, pd.MultiIndex) else df.copy()
    if 'permno' not in df_reset.columns:
        raise ValueError("Dataframe must have 'permno' as a column or index level.")

    grouped = df_reset.groupby('permno')
    dfs_list = [group for _, group in grouped]

    return unique_mappings,dfs_list 



print(dfb.columns)

display(dfb)
unique_mappings_b,dfs_list_b =map_permno_to_ticker(dfb)
display(unique_mappings_b)


display(dfa)
unique_mappings_a,dfs_list_a =map_permno_to_ticker(dfa)
display(unique_mappings_a)




out=dfb.copy()
out = out.groupby(level='permno').apply(lambda g: g.ffill())
out.index = out.index.droplevel(0)

unique_mappings_out,dfs_list_out =map_permno_to_ticker(out)
display(unique_mappings_out)

Index(['bidlo', 'askhi', 'prc', 'vol', 'ret', 'bid', 'ask', 'shrout', 'cfacpr',
       'cfacshr', 'openprc', 'numtrd', 'retx', 'adj_prc', 'adj_shrout',
       'adj_mktcap', 'ticker', 'ncusip', 'mktrf', 'smb', 'hml', 'rf', 'umd',
       'currency', 'periodicity', 'fpi', 'n_analysts', 'n_up', 'n_down',
       'cons_mean', 'cons_median', 'cons_stdev', 'cons_high', 'cons_low',
       'cons_cv', 'cons_range_pct', 'pdicity', 'act_measure', 'act_value',
       'curr_act', 'anntims', 'actdats', 'acttims', 'pends'],
      dtype='object')

C:\Users\navid\AppData\Local\Temp\ipykernel_26868\952270785.py:5: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  dfa=pd.read_csv('temp_files\\df_prices_after_fill.csv')

,,bidlo,askhi,prc,vol,ret,bid,ask,shrout,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker,ncusip,mktrf,smb,hml,rf,umd,currency,periodicity,fpi,n_analysts,n_up,n_down,cons_mean,cons_median,cons_stdev,cons_high,cons_low,cons_cv,cons_range_pct,pdicity,act_measure,act_value,curr_act,anntims,actdats,acttims,pends
date,permno,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-01-04,10104,35.36000,36.01000,35.75000,18784386.0,-0.017246,35.75000,35.76000,4201220.0,1.0,1.0,36.01000,NaN,-0.021352,35.75000,4201220.0,1.501936e+08,ORCL,68389X10,-0.0159,-0.0087,0.0052,0.0,-0.0193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-05,10104,35.49000,36.12000,35.64000,25340678.0,-0.003077,35.63000,35.64000,4201220.0,1.0,1.0,35.86000,NaN,-0.003077,35.64000,4201220.0,1.497315e+08,ORCL,68389X10,0.0013,-0.0018,0.0000,0.0,0.0066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-06,10104,35.36000,36.13500,35.82000,18165714.0,0.005051,35.83000,35.84000,4201220.0,1.0,1.0,35.50000,NaN,0.005051,35.82000,4201220.0,1.504877e+08,ORCL,68389X10,-0.0135,-0.0013,0.0001,0.0,0.0187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-07,10104,34.88000,35.68000,35.04000,22591403.0,-0.021776,35.05000,35.06000,4201220.0,1.0,1.0,35.25000,NaN,-0.021776,35.04000,4201220.0,1.472107e+08,ORCL,68389X10,-0.0244,-0.0030,0.0008,0.0,0.0084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-08,10104,34.61000,35.28000,34.65000,21962204.0,-0.011130,34.65000,34.66000,4201220.0,1.0,1.0,35.13000,NaN,-0.011130,34.65000,4201220.0,1.455723e+08,ORCL,68389X10,-0.0111,-0.0049,-0.0003,0.0,-0.0009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-24,93436,641.00000,666.09003,661.77002,22813214.0,0.024444,661.62000,661.78003,947901.0,3.0,3.0,642.98999,465870.0,0.024444,1985.31006,2843703.0,5.645632e+09,TSLA,88160R10,0.0023,-0.0040,-0.0019,0.0,0.0021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-28,93436,660.79999,681.40002,663.69000,32232732.0,0.002901,663.59998,663.77002,947901.0,3.0,3.0,674.51001,631681.0,0.002901,1991.07000,2843703.0,5.662012e+09,TSLA,88160R10,0.0049,-0.0073,0.0036,0.0,-0.0048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-29,93436,655.00000,669.90002,665.98999,22867542.0,0.003465,665.82001,665.97998,947901.0,3.0,3.0,661.00000,466884.0,0.003465,1997.96997,2843703.0,5.681633e+09,TSLA,88160R10,-0.0039,-0.0152,0.0024,0.0,-0.0041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-30,93436,668.36029,696.59998,694.78003,42766263.0,0.043229,694.64001,694.78003,947901.0,3.0,3.0,672.00000,767565.0,0.043229,2084.34009,2843703.0,5.927244e+09,TSLA,88160R10,0.0027,0.0101,0.0006,0.0,-0.0025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-31,93436,691.12000,718.71997,705.66998,49544141.0,0.015674,705.21002,705.50000,959854.0,3.0,3.0,699.98999,917115.0,0.015674,2117.00994,2879562.0,6.096061e+09,TSLA,88160R10,0.0040,-0.0086,0.0044,0.0,-0.0058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

        permno ticker
0        10104   ORCL
1259     10107   MSFT
2518     10145    HON
3777     10696   FISV
5036     11308     KO
...        ...    ...
116855   92602     PM
118114   92611      V
119373   92655    UNH
120632   93002   AVGO
121891   93436   TSLA

[103 rows x 2 columns]

,,bidlo,askhi,prc,vol,ret,bid,ask,shrout,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker,ncusip,mktrf,smb,hml,rf,umd,currency,periodicity,fpi,n_analysts,n_up,n_down,cons_mean,cons_median,cons_stdev,cons_high,cons_low,cons_cv,cons_range_pct,pdicity,act_measure,act_value,curr_act,anntims,actdats,acttims,pends
date,permno,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-03-15,10104,38.13000,38.87000,38.74000,17502867.0,0.001034,38.74000,38.75000,4201220.0,1.0,1.0,38.35000,-9999.0,0.001034,38.74000,4201220.0,1.627553e+08,ORCL,68389X10,-0.0035,-0.0149,0.0069,0.00001,0.0208,USD,LTG,0,7.0,0.0,1.0,7.95,6.50,4.48,15.00,2.8,0.563522,1.534591,QTR,EPS,0.64,USD,16:00:00,2016-03-15 00:00:00,16:09:10,2016-02-29
2016-03-16,10104,39.53000,40.94500,40.22000,49082261.0,0.038203,40.22000,40.23000,4201220.0,1.0,1.0,39.55000,-9999.0,0.038203,40.22000,4201220.0,1.689731e+08,ORCL,68389X10,0.0063,0.0011,-0.0009,0.00001,-0.0118,USD,LTG,0,7.0,0.0,1.0,7.95,6.50,4.48,15.00,2.8,0.563522,1.534591,QTR,EPS,0.64,USD,16:00:00,2016-03-15 00:00:00,16:09:10,2016-02-29
2016-03-17,10104,40.07000,40.96000,40.61000,22163514.0,0.009697,40.62000,40.63000,4201220.0,1.0,1.0,40.15000,-9999.0,0.009697,40.61000,4201220.0,1.706115e+08,ORCL,68389X10,0.0071,0.0083,0.0059,0.00001,-0.0093,USD,LTG,0,7.0,0.0,2.0,7.79,6.50,4.67,15.00,2.3,0.599487,1.630295,QTR,EPS,0.64,USD,16:00:00,2016-03-15 00:00:00,16:09:10,2016-02-29
2016-03-18,10104,40.65000,41.49000,41.48000,34354028.0,0.021423,41.46000,41.47000,4201220.0,1.0,1.0,40.87000,-9999.0,0.021423,41.48000,4201220.0,1.742666e+08,ORCL,68389X10,0.0054,0.0037,-0.0014,0.00001,-0.0089,USD,LTG,0,7.0,0.0,2.0,7.79,6.50,4.67,15.00,2.3,0.599487,1.630295,QTR,EPS,0.64,USD,16:00:00,2016-03-15 00:00:00,16:09:10,2016-02-29
2016-03-21,10104,41.37000,42.00000,41.61000,17275055.0,0.003134,41.60000,41.61000,4201220.0,1.0,1.0,41.42000,-9999.0,0.003134,41.61000,4201220.0,1.748128e+08,ORCL,68389X10,0.0010,-0.0022,-0.0033,0.00001,-0.0013,USD,LTG,0,7.0,0.0,2.0,7.79,6.50,4.67,15.00,2.3,0.599487,1.630295,QTR,EPS,0.64,USD,16:00:00,2016-03-15 00:00:00,16:09:10,2016-02-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-24,93436,641.00000,666.09003,661.77002,22813214.0,0.024444,661.62000,661.78003,947901.0,3.0,3.0,642.98999,465870.0,0.024444,1985.31006,2843703.0,5.645632e+09,TSLA,88160R10,0.0023,-0.0040,-0.0019,0.00000,0.0021,USD,LTG,0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21 00:00:00,16:42:05,2020-09-30
2020-12-28,93436,660.79999,681.40002,663.69000,32232732.0,0.002901,663.59998,663.77002,947901.0,3.0,3.0,674.51001,631681.0,0.002901,1991.07000,2843703.0,5.662012e+09,TSLA,88160R10,0.0049,-0.0073,0.0036,0.00000,-0.0048,USD,LTG,0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21 00:00:00,16:42:05,2020-09-30
2020-12-29,93436,655.00000,669.90002,665.98999,22867542.0,0.003465,665.82001,665.97998,947901.0,3.0,3.0,661.00000,466884.0,0.003465,1997.96997,2843703.0,5.681633e+09,TSLA,88160R10,-0.0039,-0.0152,0.0024,0.00000,-0.0041,USD,LTG,0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21 00:00:00,16:42:05,2020-09-30
2020-12-30,93436,668.36029,696.59998,694.78003,42766263.0,0.043229,694.64001,694.78003,947901.0,3.0,3.0,672.00000,767565.0,0.043229,2084.34009,2843703.0,5.927244e+09,TSLA,88160R10,0.0027,0.0101,0.0006,0.00000,-0.0025,USD,LTG,0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21 00:00:00,16:42:05,2020-09-30
2020-12-31,93436,691.12000,718.71997,705.66998,49544141.0,0.015674,705.21002,705.50000,959854.0,3.0,3.0,699.98999,917115.0,0.015674,2117.00994,2879562.0,6.096061e+09,TSLA,88160R10,0.0040,-0.0086,0.0044,0.00000,-0.0058,USD,LTG,0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21 00:00:00,16:42:05,2020-09-30

        permno ticker
0        10104   ORCL
1210     10107   MSFT
2452     10145    HON
3703     10696   FISV
4954     11308     KO
...        ...    ...
114103   92602     PM
115354   92611      V
116605   92655    UNH
117856   93002   AVGO
119107   93436   TSLA

[103 rows x 2 columns]

C:\Users\navid\AppData\Local\Temp\ipykernel_26868\952270785.py:44: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  out = out.groupby(level='permno').apply(lambda g: g.ffill())

        permno ticker
0        10104   ORCL
1259     10107   MSFT
2518     10145    HON
3777     10696   FISV
5036     11308     KO
...        ...    ...
116855   92602     PM
118114   92611      V
119373   92655    UNH
120632   93002   AVGO
121891   93436   TSLA

[103 rows x 2 columns]

In [68]:
wo=dfs_list_out[1].copy()
print(len(wo))
print(wo['pdicity'].isna().sum())
wo=wo.dropna(axis=1, how='all').ffill()
display(wo)
n=len(wo.columns)
counter=0
for i in wo.index:
    if wo.loc[i,:].isna().sum() >0:
        print(i)
        counter+=1
print(counter)

1259
1259

,date,permno,bidlo,askhi,prc,vol,ret,bid,ask,shrout,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker,ncusip,mktrf,smb,hml,rf,umd,currency,periodicity,fpi,n_analysts,n_up,n_down,cons_mean,cons_median,cons_stdev,cons_high,cons_low,cons_cv,cons_range_pct
1259,2016-01-04,13407,99.75000,102.24000,102.22000,37912403.0,-0.023314,102.20000,102.22000,2294940.0,1.0,1.0,101.95000,235462.0,-0.023314,102.22000,2294940.0,2.345888e+08,FB,30303M10,-0.0159,-0.0087,0.0052,0.0,-0.0193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1260,2016-01-05,13407,101.66500,103.70990,102.73000,23258238.0,0.004989,102.73000,102.74000,2294940.0,1.0,1.0,102.89000,143816.0,0.004989,102.73000,2294940.0,2.357592e+08,FB,30303M10,0.0013,-0.0018,0.0000,0.0,0.0066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1261,2016-01-06,13407,100.90000,103.77000,102.97000,25096183.0,0.002336,102.97000,102.98000,2294940.0,1.0,1.0,101.13000,152633.0,0.002336,102.97000,2294940.0,2.363100e+08,FB,30303M10,-0.0135,-0.0013,0.0001,0.0,0.0187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1262,2016-01-07,13407,97.30000,101.43000,97.92000,45172501.0,-0.049043,97.92000,97.93000,2294940.0,1.0,1.0,100.50000,272751.0,-0.049043,97.92000,2294940.0,2.247205e+08,FB,30303M10,-0.0244,-0.0030,0.0008,0.0,0.0084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1263,2016-01-08,13407,97.03110,100.50000,97.33000,35702298.0,-0.006025,97.32000,97.34000,2294940.0,1.0,1.0,99.88000,205216.0,-0.006025,97.33000,2294940.0,2.233665e+08,FB,30303M10,-0.0111,-0.0049,-0.0003,0.0,-0.0009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,2020-12-24,13407,266.20001,270.39999,267.39999,6624701.0,-0.002648,267.32001,267.39999,2403969.0,1.0,1.0,268.87500,81819.0,-0.002648,267.39999,2403969.0,6.428213e+08,FB,30303M10,0.0023,-0.0040,-0.0019,0.0,0.0021,USD,LTG,0.0,2.0,0.0,0.0,16.6,16.6,6.93,21.5,11.7,0.41747,0.590361
2514,2020-12-28,13407,265.66000,277.29999,277.00000,23265734.0,0.035901,277.00000,277.07999,2403969.0,1.0,1.0,268.73999,238060.0,0.035901,277.00000,2403969.0,6.658994e+08,FB,30303M10,0.0049,-0.0073,0.0036,0.0,-0.0048,USD,LTG,0.0,2.0,0.0,0.0,16.6,16.6,6.93,21.5,11.7,0.41747,0.590361
2515,2020-12-29,13407,276.28000,280.51001,276.78000,16351373.0,-0.000794,276.78000,276.91000,2403969.0,1.0,1.0,276.95001,192840.0,-0.000794,276.78000,2403969.0,6.653705e+08,FB,30303M10,-0.0039,-0.0152,0.0024,0.0,-0.0041,USD,LTG,0.0,2.0,0.0,0.0,16.6,16.6,6.93,21.5,11.7,0.41747,0.590361
2516,2020-12-30,13407,271.70999,278.07999,271.87000,11887488.0,-0.017740,271.87000,271.88000,2403969.0,1.0,1.0,277.95001,147259.0,-0.017740,271.87000,2403969.0,6.535671e+08,FB,30303M10,0.0027,0.0101,0.0006,0.0,-0.0025,USD,LTG,0.0,2.0,0.0,0.0,16.6,16.6,6.93,21.5,11.7,0.41747,0.590361
2517,2020-12-31,13407,269.81000,277.09000,273.16000,12853391.0,0.004745,273.01001,273.16000,2406000.0,1.0,1.0,272.00000,145976.0,0.004745,273.16000,2406000.0,6.572230e+08,FB,30303M10,0.0040,-0.0086,0.0044,0.0,-0.0058,USD,LTG,0.0,2.0,0.0,0.0,16.6,16.6,6.93,21.5,11.7,0.41747,0.590361

1259
1260
1261
1262
1263
1264
1265
1266
8

In [71]:
wo=out.copy()
wo = wo.groupby(level='permno').apply(lambda g: g.dropna(axis=1, how='all').ffill())
wo.index = wo.index.droplevel(0)

mask = ~wo.isna().any(axis=1)
group_cumsum = mask.groupby(wo.index.get_level_values('permno')).cumsum()
wo = wo[group_cumsum > 0]
wo

,,bidlo,askhi,prc,vol,ret,bid,ask,shrout,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker,ncusip,mktrf,smb,hml,rf,umd,currency,periodicity,fpi,n_analysts,n_up,n_down,cons_mean,cons_median,cons_stdev,cons_high,cons_low,cons_cv,cons_range_pct,pdicity,act_measure,act_value,curr_act,anntims,actdats,acttims,pends
date,permno,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-01-28,10107,51.25000,52.21000,52.05500,62515470.0,0.016302,52.05000,52.06000,7909303.0,1.0,1.0,51.86000,329904.0,0.016302,52.05500,7909303.0,4.117188e+08,MSFT,59491810,0.0049,-0.0047,0.0126,0.00000,0.0046,USD,LTG,0.0,6.0,0.0,0.0,9.13,9.65,2.63,12.30,6.0,0.288061,0.690033,QTR,EPS,0.78,USD,16:06:00,2016-01-28,16:18:49,2015-12-31
2016-01-29,10107,54.00000,55.09000,55.09000,83611686.0,0.058304,55.04000,55.05000,7909303.0,1.0,1.0,54.73000,366358.0,0.058304,55.09000,7909303.0,4.357235e+08,MSFT,59491810,0.0257,0.0048,0.0042,0.00000,-0.0120,USD,LTG,0.0,6.0,0.0,0.0,9.13,9.65,2.63,12.30,6.0,0.288061,0.690033,QTR,EPS,0.78,USD,16:06:00,2016-01-28,16:18:49,2015-12-31
2016-02-01,10107,54.49500,55.09000,54.71000,44208542.0,-0.006898,54.67000,54.69000,7909303.0,1.0,1.0,54.88000,221184.0,-0.006898,54.71000,7909303.0,4.327180e+08,MSFT,59491810,-0.0004,-0.0019,-0.0100,0.00001,0.0031,USD,LTG,0.0,6.0,0.0,0.0,9.13,9.65,2.63,12.30,6.0,0.288061,0.690033,QTR,EPS,0.78,USD,16:06:00,2016-01-28,16:18:49,2015-12-31
2016-02-02,10107,52.65000,54.26000,53.00000,56313803.0,-0.031256,52.99000,53.00000,7909303.0,1.0,1.0,54.17000,282402.0,-0.031256,53.00000,7909303.0,4.191931e+08,MSFT,59491810,-0.0200,-0.0003,-0.0036,0.00001,0.0125,USD,LTG,0.0,6.0,0.0,0.0,9.13,9.65,2.63,12.30,6.0,0.288061,0.690033,QTR,EPS,0.78,USD,16:06:00,2016-01-28,16:18:49,2015-12-31
2016-02-03,10107,51.26000,53.39000,52.16000,57559814.0,-0.015849,52.14000,52.16000,7909303.0,1.0,1.0,53.25000,323502.0,-0.015849,52.16000,7909303.0,4.125492e+08,MSFT,59491810,0.0046,-0.0033,0.0045,0.00001,-0.0244,USD,LTG,0.0,6.0,0.0,0.0,9.13,9.65,2.63,12.30,6.0,0.288061,0.690033,QTR,EPS,0.78,USD,16:06:00,2016-01-28,16:18:49,2015-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-24,93436,641.00000,666.09003,661.77002,22813214.0,0.024444,661.62000,661.78003,947901.0,3.0,3.0,642.98999,465870.0,0.024444,1985.31006,2843703.0,5.645632e+09,TSLA,88160R10,0.0023,-0.0040,-0.0019,0.00000,0.0021,USD,LTG,0.0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21,16:42:05,2020-09-30
2020-12-28,93436,660.79999,681.40002,663.69000,32232732.0,0.002901,663.59998,663.77002,947901.0,3.0,3.0,674.51001,631681.0,0.002901,1991.07000,2843703.0,5.662012e+09,TSLA,88160R10,0.0049,-0.0073,0.0036,0.00000,-0.0048,USD,LTG,0.0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21,16:42:05,2020-09-30
2020-12-29,93436,655.00000,669.90002,665.98999,22867542.0,0.003465,665.82001,665.97998,947901.0,3.0,3.0,661.00000,466884.0,0.003465,1997.96997,2843703.0,5.681633e+09,TSLA,88160R10,-0.0039,-0.0152,0.0024,0.00000,-0.0041,USD,LTG,0.0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21,16:42:05,2020-09-30
2020-12-30,93436,668.36029,696.59998,694.78003,42766263.0,0.043229,694.64001,694.78003,947901.0,3.0,3.0,672.00000,767565.0,0.043229,2084.34009,2843703.0,5.927244e+09,TSLA,88160R10,0.0027,0.0101,0.0006,0.00000,-0.0025,USD,LTG,0.0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21,16:42:05,2020-09-30
2020-12-31,93436,691.12000,718.71997,705.66998,49544141.0,0.015674,705.21002,705.50000,959854.0,3.0,3.0,699.98999,917115.0,0.015674,2117.00994,2879562.0,6.096061e+09,TSLA,88160R10,0.0040,-0.0086,0.0044,0.00000,-0.0058,USD,LTG,0.0,3.0,0.0,1.0,353.90,407.94,120.17,437.55,216.2,0.339559,0.625459,QTR,EPS,0.76,USD,16:07:00,2020-10-21,16:42:05,2020-09-30

In [62]:
df['pdicity'].isna().sum()

np.int64(1259)

In [70]:

df=dfs_list_out[1]

print('len:',len(df))
na_counts = df.isna().sum()
na_columns = na_counts[na_counts > 0]
print("Columns with NA values and their counts:")
print(na_columns)
s=df['currency']
display(df[~s.isna()].loc[:,['date','currency','periodicity']])


# na_counts = dfs_list_out[0].isna().sum()
# na_columns = na_counts[na_counts > 0]
# print("Columns with NA values and their counts:")
# print(na_columns)
# s=dfs_list_out[0]['currency']
# display(dfs_list_out[0][~s.isna()].loc[:,['date','currency','periodicity']])

len: 1259
Columns with NA values and their counts:
currency             8
periodicity          8
fpi                  8
n_analysts           8
n_up                 8
n_down               8
cons_mean            8
cons_median          8
cons_stdev           8
cons_high            8
cons_low             8
cons_cv              8
cons_range_pct       8
pdicity           1259
act_measure       1259
act_value         1259
curr_act          1259
anntims           1259
actdats           1259
acttims           1259
pends             1259
dtype: int64

            date currency periodicity
1267  2016-01-14      USD         LTG
1268  2016-01-15      USD         LTG
1269  2016-01-19      USD         LTG
1270  2016-01-20      USD         LTG
1271  2016-01-21      USD         LTG
...          ...      ...         ...
2513  2020-12-24      USD         LTG
2514  2020-12-28      USD         LTG
2515  2020-12-29      USD         LTG
2516  2020-12-30      USD         LTG
2517  2020-12-31      USD         LTG

[1251 rows x 3 columns]

In [3]:
pd.set_option('display.max_columns', None)
# Group by 'permno' level of the multi-index
permno_groups = dict(tuple(dfb.groupby(level='permno')))

# # Now you can access each group by its permno key, for example:
# some_permno = list(permno_groups.keys())[0]
# group_df = permno_groups[some_permno]

# Extract Apple's data using its permno 14593
df_apple = permno_groups.get(14593)

# Now df_apple contains the data only for Apple
print(len(df_apple))
df_apple.head()

1259

,,bidlo,askhi,prc,vol,ret,bid,ask,shrout,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker,ncusip,mktrf,smb,hml,rf,umd,currency,periodicity,fpi,n_analysts,n_up,n_down,cons_mean,cons_median,cons_stdev,cons_high,cons_low,cons_cv,cons_range_pct,pdicity,act_measure,act_value,curr_act,anntims,actdats,acttims,pends
date,permno,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-01-04,14593,102.00,105.368,105.35,69383612.0,0.000855,105.33,105.35,5544487.0,4.0,4.0,102.61,354165.0,0.000855,421.40,22177948.0,9.345787e+09,AAPL,03783310,-0.0159,-0.0087,0.0052,0.0,-0.0193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-05,14593,102.41,105.850,102.71,55791042.0,-0.025059,102.70,102.71,5544487.0,4.0,4.0,105.75,322695.0,-0.025059,410.84,22177948.0,9.111588e+09,AAPL,03783310,0.0013,-0.0018,0.0000,0.0,0.0066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-06,14593,99.87,102.370,100.70,68487388.0,-0.019570,100.67,100.70,5544487.0,4.0,4.0,100.56,411776.0,-0.019570,402.80,22177948.0,8.933277e+09,AAPL,03783310,-0.0135,-0.0013,0.0001,0.0,0.0187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-07,14593,96.43,100.130,96.45,81466204.0,-0.042205,96.44,96.54,5544487.0,4.0,4.0,98.68,466604.0,-0.042205,385.80,22177948.0,8.556252e+09,AAPL,03783310,-0.0244,-0.0030,0.0008,0.0,0.0084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-08,14593,96.76,99.110,96.96,70798746.0,0.005288,96.98,96.99,5544583.0,4.0,4.0,98.55,422522.0,0.005288,387.84,22178332.0,8.601644e+09,AAPL,03783310,-0.0111,-0.0049,-0.0003,0.0,-0.0009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# df_apple.dropna()
# Count the number of NaNs in each column
na_counts = df_apple.isna().sum()
# Filter to keep only columns with at least one NaN
na_columns = na_counts[na_counts > 0]

print("Columns with NA values and their counts:")
print(na_columns)

Columns with NA values and their counts:
currency          1199
periodicity       1199
fpi               1199
n_analysts        1199
n_up              1199
n_down            1199
cons_mean         1199
cons_median       1199
cons_stdev        1199
cons_high         1199
cons_low          1199
fpe_date          1259
cons_cv           1199
cons_range_pct    1199
pdicity           1239
act_measure       1239
act_value         1239
curr_act          1239
anntims           1239
actdats           1239
acttims           1239
pends             1239
dtype: int64

In [23]:

out = dfb.copy()
indices_to_drop = []

# Group by permno level (assumed MultiIndex)
for permno, group in out.groupby(level="permno"):
    # Find first row index with no NaNs (all columns complete)
    complete_rows = group.dropna(how='any')
    if complete_rows.empty:
        # No complete row in group, drop entire group
        indices_to_drop.extend(group.index)
    else:
        first_complete_idx = complete_rows.index[0]
        # Drop all rows before first_complete_idx (exclusive)
        rows_to_drop = group.loc[:first_complete_idx].index[:-1]  # exclude first_complete_idx itself
        indices_to_drop.extend(rows_to_drop)

# Drop identified leading NaN rows from original dataframe
out.drop(index=indices_to_drop, inplace=True)
out = out.groupby(level="permno").apply(lambda g: g.ffill())
out.index = out.index.droplevel(0)  # remove groupby added index level

# Calculate and print average percentage of rows removed
total_rows = len(df)
removed_pct = len(indices_to_drop) / total_rows * 100 if total_rows else 0
print(f"Average percentage of rows removed per group due to leading NaNs: {removed_pct:.2f}%")

# Check for remaining NaNs
if out.isna().any().any():
    print("WARNING: There are still NaN values present after forward fill.")
else:
    print("INFO: No NaN values remain after forward fill.")

Average percentage of rows removed per group due to leading NaNs: 98.50%
INFO: No NaN values remain after forward fill.

In [24]:
print(len( dfb ))
len(out)

1735711

26051

In [11]:

print(len(dfb[dfb.isna().any(axis=1)]))
print(len(dfa[dfa.isna().any(axis=1)]))

1735533
1407247

In [74]:
import pandas as pd
# dsf = pd.read_parquet('wrds_extracts\\run_20250914_133747\\dsf.parquet')
# names = pd.read_parquet('wrds_extracts\\run_20250914_133747\\stocknames.parquet')
# df_prices= pd.read_csv('temp_files\\df_prices.csv')
# df_prices2= pd.read_csv('temp_files\\df_prices2.csv')
ibes = pd.read_parquet('wrds_extracts\\run_20250914_133747\\ibes_stats.parquet')
ibes2 = pd.read_parquet('wrds_extracts\\run_20250914_133747\\ibes_act.parquet')

ibes2

,ticker,cusip,oftic,cname,anndats,anntims,actdats,acttims,pends,pdicity,act_measure,act_value,curr_act,usfirm
0,0000,None,None,None,2014-02-14,18:41:00,2014-03-10,13:41:57,2012-12-31,ANN,EPS,NaN,USD,1
1,0000,None,None,None,2014-02-14,18:41:00,2014-03-10,13:41:57,2012-12-31,QTR,EPS,NaN,USD,1
2,0000,None,None,None,2014-02-14,18:41:00,2014-03-10,05:58:45,2013-01-31,QTR,EPS,NaN,USD,1
3,0000,None,None,None,2014-02-14,18:41:00,2014-03-10,13:42:58,2013-03-31,QTR,EPS,NaN,USD,1
4,0000,None,None,None,2014-02-14,18:41:00,2014-03-10,06:11:05,2013-04-30,QTR,EPS,NaN,USD,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066195,ZYNX,98986M10,ZYXI,ZYNEX INC,2020-02-27,16:02:00,2020-02-27,17:09:16,2019-12-31,ANN,EPS,0.28,USD,1
1066196,ZYNX,98986M10,ZYXI,ZYNEX INC,2020-02-27,16:02:00,2020-02-27,17:09:16,2019-12-31,QTR,EPS,0.09,USD,1
1066197,ZYNX,98986M10,ZYXI,ZYNEX INC,2020-04-28,16:02:00,2020-04-28,17:09:14,2020-03-31,QTR,EPS,0.09,USD,1
1066198,ZYNX,98986M10,ZYXI,ZYNEX INC,2020-07-28,16:01:00,2020-07-28,16:51:29,2020-06-30,QTR,EPS,0.09,USD,1
1066199,ZYNX,98986M10,ZYXI,ZYNEX INC,2020-10-27,16:01:00,2020-10-27,16:06:34,2020-09-30,QTR,EPS,0.04,USD,1

In [75]:
ibes2.columns

Index(['ticker', 'cusip', 'oftic', 'cname', 'anndats', 'anntims', 'actdats',
       'acttims', 'pends', 'pdicity', 'act_measure', 'act_value', 'curr_act',
       'usfirm'],
      dtype='object')

In [78]:
df=ibes2.groupby(["oftic", "anndats"], dropna=False).size()
df.sort_index()

oftic  anndats
1119   1999-09-23     1
1348   2000-05-16     2
       2003-02-15     1
       2004-11-10    10
       2005-06-29     3
                     ..
NaN    2020-12-18    19
       2020-12-21     2
       2020-12-22    15
       2020-12-30     2
       2020-12-31     1
Length: 770521, dtype: int64

In [54]:
s2=df_prices2[df_prices2['ticker'].isna()]
pnos=s2['permno'].unique()
print(pnos)
df_prices2[df_prices2['permno'].isin(pnos) & df_prices2['ticker'].notna()]

[10066 11153 11379 12928 13038 13563 13755 13878 13939 14469 14675 15294
 15793 16086 16402 16773 18065 29744 32791 52231 76928 77263 77624 78690
 78988 79280 82156 82745 83577 83840 84321 84411 85377 85399 85953 86812
 86866 87043 87404 88937 88987 89169 89986 91135 91283 91305 91428 91522
 91907 91910 92218 92683 93338]

,permno,date,bidlo,askhi,prc,vol,ret,bid,ask,shrout,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker,ncusip
20966,11379,2020-01-02,1.2800,1.3100,1.2900,27720.0,0.007812,1.2900,1.3000,50349.0,1.0,1.0,1.2800,129.0,0.007812,1.2900,50349.0,64950.2100,DXLG,25065K10
20967,11379,2020-01-03,1.2800,1.3100,1.2800,32181.0,-0.007752,1.2800,1.3000,50349.0,1.0,1.0,1.2900,119.0,-0.007752,1.2800,50349.0,64446.7200,DXLG,25065K10
20968,11379,2020-01-06,1.2500,1.2962,1.2500,68734.0,-0.023438,1.1800,1.2400,50349.0,1.0,1.0,1.2800,181.0,-0.023438,1.2500,50349.0,62936.2500,DXLG,25065K10
20969,11379,2020-01-07,1.2400,1.2800,1.2400,12480.0,-0.008000,1.2400,1.2500,50349.0,1.0,1.0,1.2800,108.0,-0.008000,1.2400,50349.0,62432.7600,DXLG,25065K10
20970,11379,2020-01-08,1.0948,1.2500,1.1200,139349.0,-0.096774,1.0900,1.1200,50349.0,1.0,1.0,1.2500,296.0,-0.096774,1.1200,50349.0,56390.8800,DXLG,25065K10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737696,93338,2020-06-15,0.5420,0.6100,0.5769,4011057.0,0.013172,0.5700,0.5701,100235.0,1.0,1.0,0.5600,NaN,0.013172,0.5769,100235.0,57825.5715,SDRL,G7998G10
1737697,93338,2020-06-16,0.5801,0.6500,0.5897,6211186.0,0.022188,0.5930,0.5933,100235.0,1.0,1.0,0.6500,NaN,0.022188,0.5897,100235.0,59108.5795,SDRL,G7998G10
1737698,93338,2020-06-17,0.5490,0.5950,0.5562,1828730.0,-0.056809,0.5526,0.5562,100235.0,1.0,1.0,0.5800,NaN,-0.056809,0.5562,100235.0,55750.7070,SDRL,G7998G10
1737699,93338,2020-06-18,0.5214,0.5898,0.5470,2752583.0,-0.016541,0.5460,0.5461,100235.0,1.0,1.0,0.5667,NaN,-0.016541,0.5470,100235.0,54828.5450,SDRL,G7998G10
1737700,93338,2020-06-19,0.5020,0.5794,0.5097,9436256.0,-0.068190,0.5200,0.5201,100330.0,1.0,1.0,0.5700,NaN,-0.068190,0.5097,100330.0,51138.2010,SDRL,G7998G10

In [55]:
for permno in pnos:
    rows = names[names['permno'] == permno].sort_values('namedt')
    print(f"Permno: {permno}")
    print(rows[['permno', 'ticker', 'namedt', 'nameenddt']])
    print("-"*50)

Permno: 10066
   permno ticker      namedt   nameenddt
7   10066   None  2008-01-22  2021-03-28
--------------------------------------------------
Permno: 11153
    permno ticker      namedt   nameenddt
78   11153   None  1992-04-06  2021-08-26
--------------------------------------------------
Permno: 11379
     permno ticker      namedt   nameenddt
100   11379   DXLG  2013-02-25  2020-12-21
101   11379   None  2020-12-22  2021-09-07
--------------------------------------------------
Permno: 12928
     permno ticker      namedt   nameenddt
486   12928   None  2016-12-27  2022-02-08
--------------------------------------------------
Permno: 13038
     permno ticker      namedt   nameenddt
537   13038   None  2018-04-27  2021-05-24
--------------------------------------------------
Permno: 13563
     permno ticker      namedt   nameenddt
769   13563   None  2019-11-11  2021-06-16
--------------------------------------------------
Permno: 13755
     permno ticker      namedt   nameenddt
864   13755   None  2017-08-07  2020-09-13
865   13755   None  2020-09-14  2020-09-17
866   13755   HGEN  2020-09-18  2023-07-25
--------------------------------------------------
Permno: 13878
     permno ticker      namedt   nameenddt
947   13878   None  2018-11-08  2020-11-03
948   13878   MDXG  2020-11-04  2024-12-31
--------------------------------------------------
Permno: 13939
     permno ticker      namedt   nameenddt
983   13939   None  2017-04-19  2024-12-25
--------------------------------------------------
Permno: 14469
      permno ticker      namedt   nameenddt
1296   14469   None  2016-08-11  2021-09-27
--------------------------------------------------
Permno: 14675
      permno ticker      namedt   nameenddt
1433   14675   TGEN  2014-05-20  2020-06-08
1434   14675   None  2020-06-09  2020-06-09
1435   14675   TGEN  2020-06-10  2020-06-18
--------------------------------------------------
Permno: 15294
      permno ticker      namedt   nameenddt
1817   15294   KMPH  2015-04-16  2020-05-20
1818   15294   None  2020-05-21  2020-12-27
1819   15294   None  2020-12-28  2021-01-07
--------------------------------------------------
Permno: 15793
      permno ticker      namedt   nameenddt
2102   15793   PMTS  2017-12-20  2020-01-16
2103   15793   None  2020-01-17  2021-08-04
--------------------------------------------------
Permno: 16086
      permno ticker      namedt   nameenddt
2265   16086    HTZ  2016-07-01  2020-02-23
2266   16086    HTZ  2020-02-24  2020-10-29
2267   16086   None  2020-10-30  2021-06-29
--------------------------------------------------
Permno: 16402
      permno ticker      namedt   nameenddt
2429   16402    XOG  2016-10-12  2020-06-24
2430   16402   None  2020-06-25  2021-01-20
--------------------------------------------------
Permno: 16773
      permno ticker      namedt   nameenddt
2657   16773   None  2019-08-22  2021-10-20
--------------------------------------------------
Permno: 18065
      permno ticker      namedt   nameenddt
3591   18065    GTX  2018-10-01  2020-09-20
3592   18065   None  2020-09-21  2021-05-02
--------------------------------------------------
Permno: 29744
      permno ticker      namedt   nameenddt
5471   29744   None  2017-08-21  2021-02-10
--------------------------------------------------
Permno: 32791
      permno ticker      namedt   nameenddt
5499   32791   None  2019-12-13  2021-06-01
--------------------------------------------------
Permno: 52231
      permno ticker      namedt   nameenddt
5697   52231   None  2009-04-27  2021-03-22
--------------------------------------------------
Permno: 76928
      permno ticker      namedt   nameenddt
6194   76928   None  2019-05-10  2020-11-01
6195   76928   SMTI  2020-11-02  2024-12-31
--------------------------------------------------
Permno: 77263
      permno ticker      namedt   nameenddt
6236   77263   None  2008-12-11  2022-11-01
--------------------------------------------------
Permno: 77624
      permno ticker      namedt   nameenddt
6297   77624   None  2006-10-12  2020-10-08
6298   77624   INTZ  2020-10-09  2024-03-24
--------------------------------------------------
Permno: 78690
      permno ticker      namedt   nameenddt
6381   78690   None  2016-10-05  2021-12-19
--------------------------------------------------
Permno: 78988
      permno ticker      namedt   nameenddt
6423   78988   None  2013-08-29  2020-08-30
6424   78988   HGBL  2020-08-31  2024-12-31
--------------------------------------------------
Permno: 79280
      permno ticker      namedt   nameenddt
6472   79280   None  2019-02-15  2021-03-24
--------------------------------------------------
Permno: 82156
      permno ticker      namedt   nameenddt
6744   82156   None  2017-12-22  2020-04-28
6745   82156   None  2020-04-29  2020-05-19
6746   82156   WINT  2020-05-20  2023-02-23
--------------------------------------------------
Permno: 82745
      permno ticker      namedt   nameenddt
6807   82745   None  1999-10-05  2020-11-16
6808   82745   SMID  2020-11-17  2024-12-31
--------------------------------------------------
Permno: 83577
      permno ticker      namedt   nameenddt
6885   83577   None  2008-10-01  2021-07-29
--------------------------------------------------
Permno: 83840
      permno ticker      namedt   nameenddt
6917   83840   None  2014-11-20  2021-05-23
--------------------------------------------------
Permno: 84321
      permno ticker      namedt   nameenddt
6966   84321   None  2016-07-27  2021-04-26
--------------------------------------------------
Permno: 84411
      permno ticker      namedt   nameenddt
6982   84411   None  2003-07-24  2021-08-30
--------------------------------------------------
Permno: 85377
      permno ticker      namedt   nameenddt
7072   85377   None  1999-07-28  2021-11-25
--------------------------------------------------
Permno: 85399
      permno ticker      namedt   nameenddt
7076   85399   None  2017-02-06  2020-11-30
7077   85399   POWW  2020-12-01  2024-12-31
--------------------------------------------------
Permno: 85953
      permno ticker      namedt   nameenddt
7171   85953   None  2018-12-31  2022-01-24
--------------------------------------------------
Permno: 86812
      permno ticker      namedt   nameenddt
7288   86812   None  2019-10-03  2020-10-18
7289   86812   None  2020-10-19  2021-04-28
--------------------------------------------------
Permno: 86866
      permno ticker      namedt   nameenddt
7297   86866   TUES  1999-04-22  2020-06-07
7298   86866   None  2020-06-08  2020-12-30
7299   86866   None  2020-12-31  2021-05-24
--------------------------------------------------
Permno: 87043
      permno ticker      namedt   nameenddt
7328   87043   None  2019-01-15  2020-02-02
7329   87043   QMCO  2020-02-03  2024-08-26
--------------------------------------------------
Permno: 87404
      permno ticker      namedt   nameenddt
7383   87404   None  2015-01-13  2020-07-07
7384   87404   CXDO  2020-07-08  2024-12-31
--------------------------------------------------
Permno: 88937
      permno ticker      namedt   nameenddt
7606   88937   None  2009-07-07  2022-05-23
--------------------------------------------------
Permno: 88987
      permno ticker      namedt   nameenddt
7619   88987   None  2018-06-29  2021-02-21
--------------------------------------------------
Permno: 89169
      permno ticker      namedt   nameenddt
7673   89169   None  2019-12-24  2020-04-30
7674   89169   DCTH  2020-05-01  2024-12-31
--------------------------------------------------
Permno: 89986
      permno ticker      namedt   nameenddt
7961   89986   None  2009-12-09  2021-06-15
--------------------------------------------------
Permno: 91135
      permno ticker      namedt   nameenddt
8371   91135    BTE  2016-12-22  2020-12-03
8372   91135   None  2020-12-04  2023-02-22
--------------------------------------------------
Permno: 91283
      permno ticker      namedt   nameenddt
8412   91283   None  2019-10-08  2020-02-11
8413   91283   None  2020-02-12  2020-02-19
8414   91283   BATL  2020-02-20  2024-12-31
--------------------------------------------------
Permno: 91305
      permno ticker      namedt   nameenddt
8425   91305    OBE  2019-06-10  2020-04-01
8426   91305   None  2020-04-02  2022-01-30
--------------------------------------------------
Permno: 91428
      permno ticker      namedt   nameenddt
8499   91428   None  2018-07-23  2022-01-30
--------------------------------------------------
Permno: 91522
      permno ticker      namedt   nameenddt
8525   91522   None  2012-11-02  2022-03-22
--------------------------------------------------
Permno: 91907
      permno ticker      namedt   nameenddt
8698   91907   None  2018-08-23  2020-01-13
8699   91907   SMCI  2020-01-14  2024-09-30
--------------------------------------------------
Permno: 91910
      permno ticker      namedt   nameenddt
8702   91910   None  2019-09-26  2020-11-18
8703   91910   USAT  2020-11-19  2021-04-18
--------------------------------------------------
Permno: 92218
      permno ticker      namedt   nameenddt
8811   92218   None  2013-06-13  2024-11-13
--------------------------------------------------
Permno: 92683
      permno ticker      namedt   nameenddt
8994   92683   None  2019-05-21  2021-11-03
--------------------------------------------------
Permno: 93338
      permno ticker      namedt   nameenddt
9308   93338   SDRL  2018-07-03  2020-06-21
9309   93338   None  2020-06-22  2022-02-21
--------------------------------------------------

In [ ]:
l=[10066, 11153, 11379, 12928, 13038, 13563, 13755, 13878, 13939, 14469,
       14675, 15294, 15793, 16086, 16402, 16773, 18065, 29744, 32791, 52231,
       76928, 77263, 77624, 78690, 78988, 79280, 82156, 82745, 83577, 83840,
       84321, 84411, 85377, 85399, 85953, 86812, 86866, 87043, 87404, 88937,
       88987, 89169, 89986, 91135, 91283, 91305, 91428, 91522, 91907, 91910,
       92218, 92683, 93338]

#from names get the tickers for these permnos
names[names['permno'].isin(l)].sort_values(['permno','namedt'])

      permno ticker    ncusip      namedt   nameenddt
7      10066   None  35518410  2008-01-22  2021-03-28
78     11153   None  83548310  1992-04-06  2021-08-26
100    11379   DXLG  25065K10  2013-02-25  2020-12-21
101    11379   None  25065K10  2020-12-22  2021-09-07
486    12928   None  88339B10  2016-12-27  2022-02-08
...      ...    ...       ...         ...         ...
8703   91910   USAT  90328S50  2020-11-19  2021-04-18
8811   92218   None  87288V10  2013-06-13  2024-11-13
8994   92683   None  30050E10  2019-05-21  2021-11-03
9308   93338   SDRL  G7998G10  2018-07-03  2020-06-21
9309   93338   None  G7998G10  2020-06-22  2022-02-21

[86 rows x 5 columns]

In [52]:
s=df_prices[df_prices['ticker'].isna()]
pnos=s['permno'].unique()
print(pnos)
df_prices[df_prices['permno'].isin(pnos) & df_prices['ticker'].notna()]

[10066 11153 11379 12928 13038 13563 13755 13878 13939 14469 14675 15294
 15793 16086 16402 16773 18065 29744 32791 52231 76928 77263 77624 78690
 78988 79280 82156 82745 83577 83840 84321 84411 85377 85399 85953 86812
 86866 87043 87404 88937 88987 89169 89986 91135 91283 91305 91428 91522
 91907 91910 92218 92683 93338]

,permno,date,bidlo,askhi,prc,vol,ret,bid,ask,shrout,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker,ncusip
20966,11379,2020-01-02,1.2800,1.3100,1.2900,27720.0,0.007812,1.2900,1.3000,50349.0,1.0,1.0,1.2800,129.0,0.007812,1.2900,50349.0,64950.2100,DXLG,25065K10
20967,11379,2020-01-03,1.2800,1.3100,1.2800,32181.0,-0.007752,1.2800,1.3000,50349.0,1.0,1.0,1.2900,119.0,-0.007752,1.2800,50349.0,64446.7200,DXLG,25065K10
20968,11379,2020-01-06,1.2500,1.2962,1.2500,68734.0,-0.023438,1.1800,1.2400,50349.0,1.0,1.0,1.2800,181.0,-0.023438,1.2500,50349.0,62936.2500,DXLG,25065K10
20969,11379,2020-01-07,1.2400,1.2800,1.2400,12480.0,-0.008000,1.2400,1.2500,50349.0,1.0,1.0,1.2800,108.0,-0.008000,1.2400,50349.0,62432.7600,DXLG,25065K10
20970,11379,2020-01-08,1.0948,1.2500,1.1200,139349.0,-0.096774,1.0900,1.1200,50349.0,1.0,1.0,1.2500,296.0,-0.096774,1.1200,50349.0,56390.8800,DXLG,25065K10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1737696,93338,2020-06-15,0.5420,0.6100,0.5769,4011057.0,0.013172,0.5700,0.5701,100235.0,1.0,1.0,0.5600,NaN,0.013172,0.5769,100235.0,57825.5715,SDRL,G7998G10
1737697,93338,2020-06-16,0.5801,0.6500,0.5897,6211186.0,0.022188,0.5930,0.5933,100235.0,1.0,1.0,0.6500,NaN,0.022188,0.5897,100235.0,59108.5795,SDRL,G7998G10
1737698,93338,2020-06-17,0.5490,0.5950,0.5562,1828730.0,-0.056809,0.5526,0.5562,100235.0,1.0,1.0,0.5800,NaN,-0.056809,0.5562,100235.0,55750.7070,SDRL,G7998G10
1737699,93338,2020-06-18,0.5214,0.5898,0.5470,2752583.0,-0.016541,0.5460,0.5461,100235.0,1.0,1.0,0.5667,NaN,-0.016541,0.5470,100235.0,54828.5450,SDRL,G7998G10
1737700,93338,2020-06-19,0.5020,0.5794,0.5097,9436256.0,-0.068190,0.5200,0.5201,100330.0,1.0,1.0,0.5700,NaN,-0.068190,0.5097,100330.0,51138.2010,SDRL,G7998G10

In [43]:

#check if a pemno or ticker is used more than once
names[names.duplicated(subset=['permno'], keep=False)].sort_values(by=['permno', 'namedt'])

      permno ticker    ncusip      namedt   nameenddt
4      10051   HNGR  41043F20  2018-09-12  2020-02-13
5      10051   HNGR  41043F20  2020-02-14  2022-10-03
23     10253    DSS  25614T20  2016-08-26  2020-05-07
24     10253    DSS  25614T30  2020-05-08  2021-09-30
40     10514   TWMC  89336Q20  2019-08-15  2020-09-07
...      ...    ...       ...         ...         ...
9337   93370    BSL  09256U10  2020-12-21  2023-03-05
9346   93380    JKS  47759T10  2019-10-16  2020-03-01
9347   93380    JKS  47759T10  2020-03-02  2024-12-31
9353   93415    CEM  18469210  2018-10-22  2020-07-27
9354   93415    CEM  18469220  2020-07-28  2024-09-06

[1735 rows x 5 columns]

In [ ]:
import pandas as pd
import wrds

dsf = pd.read_parquet('wrds_extracts\\run_20250914_133747\\dsf.parquet')

# Enter your WRDS credentials
username = 'navid_namazi'

# Connect to WRDS with username and password
db = wrds.Connection(wrds_username=username, wrds_password=password)

# Query CRSP to get the ticker names and company names for each permno
query = """
    SELECT permno, ticker, comnam
    FROM crsp.stocknames
    WHERE permno IN ({})
""".format(",".join(map(str, dsf['permno'].unique())))

tickers = db.raw_sql(query)

# Merge ticker and company names with your dataframe on 'permno'
dsf = dsf.merge(tickers, on='permno', how='left')

dsf.head()

Loading library list...
Done

,cusip,permno,date,bidlo,askhi,prc,vol,ret,bid,ask,...,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker,comnam
0,46603210,10026,2020-01-02,181.4400,185.30,181.67999,88291.0,-0.014056,181.67,181.70,...,1.0,1.0,185.3000,2300.0,-0.014056,181.67999,18900.0,3433751.811,JJSF,J & J SNACK FOODS CORP
1,46603210,10026,2020-01-02,181.4400,185.30,181.67999,88291.0,-0.014056,181.67,181.70,...,1.0,1.0,185.3000,2300.0,-0.014056,181.67999,18900.0,3433751.811,JJSF,J & J SNACK FOODS CORP
2,29402E10,10028,2020-01-02,1.3601,1.38,1.38000,4400.0,0.022222,1.37,1.39,...,1.0,1.0,1.3601,NaN,0.022222,1.38000,26924.0,37155.120,MINT,CANYON STATE CORP
3,29402E10,10028,2020-01-02,1.3601,1.38,1.38000,4400.0,0.022222,1.37,1.39,...,1.0,1.0,1.3601,NaN,0.022222,1.38000,26924.0,37155.120,MINT,AMERICAN PACIFIC MINT INC
4,29402E10,10028,2020-01-02,1.3601,1.38,1.38000,4400.0,0.022222,1.37,1.39,...,1.0,1.0,1.3601,NaN,0.022222,1.38000,26924.0,37155.120,MINT,AMERICAN PACIFIC MINT INC

In [38]:
df=dsf[(dsf['cfacshr']==0)|(dsf['cfacpr']==0)][['permno', 'ticker', 'date', 'prc','ask','bid','cfacpr','cfacshr','comnam']]
df['permno'].value_counts()

permno
12350    2530
Name: count, dtype: int64

In [ ]:

df=dsf[dsf['prc']<0][['permno', 'ticker','comnam', 'date', 'prc','ask','bid','cfacpr','cfacshr']]
display(df)

#first count the number of rows in each group
group_counts = df['permno'].value_counts()
print(group_counts )
df = df.groupby('permno').filter(lambda x: len(x) <= 0.01 * len(dsf[dsf['permno'] == x.name]))
group_counts = df['permno'].value_counts()
print(group_counts )


df

,permno,ticker,comnam,date,prc,ask,bid,cfacpr,cfacshr
130,10294,HAVTA,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
131,10294,HVT,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
132,10294,HVT,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
133,10294,HVT,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
134,10294,HVT,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
...,...,...,...,...,...,...,...,...,...
5658263,89576,VBFC,VILLAGE BANK AND TRUST FINL CORP,2020-12-31,-34.625,36.00,33.25,1.0,1.0
5658264,89576,VBFC,VILLAGE BANK AND TRUST FINL CORP,2020-12-31,-34.625,36.00,33.25,1.0,1.0
5659337,90636,KFFB,KENTUCKY FIRST FEDERAL BANCORP,2020-12-31,-6.410,6.49,6.33,1.0,1.0
5662220,93291,SBM,PROSHARES TRUST,2020-12-31,-12.370,12.39,12.35,0.2,0.2
5662221,93291,SBM,PROSHARES TRUST,2020-12-31,-12.370,12.39,12.35,0.2,0.2

permno
62958    1211
75069    1180
64899    1098
61508    1062
10294    1056
         ...
18159       1
17067       1
20127       1
19428       1
20291       1
Name: count, Length: 1250, dtype: int64
permno
84820    30
75754    20
89812    20
83410    20
75415    16
         ..
91609     1
15946     1
18521     1
19171     1
19525     1
Name: count, Length: 222, dtype: int64

,permno,ticker,comnam,date,prc,ask,bid,cfacpr,cfacshr
390,11292,ICCC,IMMUCELL CORP,2020-01-02,-5.08,5.15,5.01,1.0,1.0
391,11292,ICCC,IMMUCELL CORP,2020-01-02,-5.08,5.15,5.01,1.0,1.0
392,11292,ICCC,IMMUCELL CORP,2020-01-02,-5.08,5.15,5.01,1.0,1.0
7684,18514,BRPM,B RILEY PRINCIPAL MERGER CORP,2020-01-02,-10.05,10.09,10.01,1.0,1.0
7685,18514,BRPM,B RILEY PRINCIPAL MERGER CORP,2020-01-02,-10.05,10.09,10.01,1.0,1.0
...,...,...,...,...,...,...,...,...,...
5554550,17030,LFEQ,VANECK E T F TRUST,2020-12-24,-34.87,34.89,34.85,1.0,1.0
5570458,92352,EFU,PROSHARES TRUST,2020-12-24,-13.19,13.21,13.17,0.5,0.5
5570459,92352,EFU,PROSHARES TRUST,2020-12-24,-13.19,13.21,13.17,0.5,0.5
5570460,92352,EFU,PROSHARES TRUST,2020-12-24,-13.19,13.21,13.17,0.5,0.5
5570461,92352,EFU,PROSHARES TRUST,2020-12-24,-13.19,13.21,13.17,0.5,0.5

In [26]:
df['comnam'].unique()

<StringArray>
[       'HAVERTY FURNITURE COS INC',                   'CYANOTECH CORP',
                    'IMMUCELL CORP',   'AIR TRANSPORTATION HLDG CO INC',
                        'AIR T INC',              'S G O C O GROUP LTD',
                  'T R O O P S INC', 'FIRST TR EXCH TRD ALPHADEX FD II',
                      'F Q F TRUST',          'A G F INVESTMENTS TRUST',
 ...
        'TURMERIC ACQUISITION CORP', 'F G NEW AMERICA ACQUISITION CORP',
                        'OPPFI INC',       'YELLOWSTONE ACQUISITION CO',
           'SKY HARBOUR GROUP CORP',         'TEKKORP DIGITAL ACQ CORP',
          'BULL HORN HOLDINGS CORP', 'COEPTIS THERAPEUTICS HOLDINGS IN',
       'SPARTACUS ACQUISITION CORP',     'EUCRATES BIOMEDICAL ACQ CORP']
Length: 1086, dtype: string